### ISSUE TITLE
github actions自動テスト実装

### ISSUE THREAD

**Issue by a2308a2308** [a2308a2308/sample_ch10#5]
## 概要
 - github actions を用いた自動テストの実装

 
## 目的
早期にCICDの仕組みを実装し、今後の開発スムーズにする。
また、CICDを理解し、共有することでチーム全体のスキルの向上に役立てる。

## マイルストーン
-  [x] Checkout code
-  [x] Rubyのセットアップ
-  [x]  Cache Ruby gemsの実装
- [x] Install dependenciesの実装
- [x] Set DATABASE_URLの実装
- [x] Setup database
- [x] config/database.ci.ymlの作成
- [x] テストの実行
- [x] Devにmerge
- [x] Mainにmerge

## 完了条件
- 自動テストがdev, mainブランチで動く

**Comment by a2308a2308** [comment]
Cache Ruby gemsの実装におけるvender/bundleは開発者がリポジトリやローカルに作成する必要はない。
github actions が動く仮想環境でのみ作成されるファイル（cache）ということらしい。

**Comment by a2308a2308** [comment]
config/database.ci.ymlは作成する必要があるが、基本的にconfig/database.ymlのコピーで良い。CICDで個別に設定する事項があれば、database.ymlの一部を書き換えてdatabase.ci.ymlとする。

**Comment by a2308a2308** [comment]
# イシュー＆ブランチの運用方法を参考にブランチを再作成
- dev_odaからfeature/#5_add_ciブランチを切った。

**Comment by a2308a2308** [comment]
## メモ
[参考サイト](https://qiita.com/JZ8xNeXY/items/fef7efb5eb9495b62faf)を見て以下を順次実装

  ```
-  [x] Checkout code

-  [x] Rubyのセットアップ
  - Ruby のバージョン、アクションのバージョンに気をつければ参考サイトのものがほぼそのまま使える。
    ```
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1 # アクション名@アクションのversion
      with:
        ruby-version: '3.2.6' 
    ```

-  [x]  Cache Ruby gemsの実装
   ```
      - name: Cache Ruby gems # Ruby gemsをキャッシュします。
       uses: actions/cache@v3
       with:
        path: vendor/bundle # キャッシュするディレクトリを指定します。
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }} # キャッシュのキーを指定します。
        restore-keys: |
         ${{ runner.os }}-gems-  # 部分一致する最新のキャッシュを探します。
   ```
-  [x] Install dependenciesの実装
  ```
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install
  ```
- [x] Set DATABASE_URLの実装
  - postgresql の DATABSE_URL を設定する.
  ```
      - name: Set DATABASE_URL
      run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/production_db" >> $GITHUB_ENV
  ```
-  [x] Setup database
   ```
    - name: Setup database
      run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:setup RAILS_ENV=test
   ```
- [x]   config/database.ci.ymlの作成
    - config/database.ci.ymlは、基本的にはconfig/database.ymlのコピー。
    - ローカルではsqliteを使用しているが、github actionsではより本番に近いほうがいいと思い以下のようにPostgreSQLでDBを設定.
    ```
    test:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %> # DATAASE_URLで本番環境のDBまたはGithub Actions環境のDBを指定
    ```


-  [x] テストの実行
  - `bundle exec rails test` でOK
  ```
   - name: Run test
     run: bundle exec rails test
  ```

## メモ
- on をpushにするかmergeの時にするか検討の必要あり。
  - pushですると毎回Github Actionsが走る。[安い](https://qiita.com/bigwheel/items/2ab7deb237122db2fb8d#%E8%9B%87%E8%B6%B3-github-actions%E5%AE%89%E3%81%99%E3%81%8E%E3%81%AA%E3%81%84)ので問題ないかと思うが過剰かも。ベストプラクティスは現状不明。
-  RAILS_ENV=productionとしてGIthub Actions でテストすることもできるが、secrete keyの設定などが必要になり少し煩雑になるので今回はconfig/database.ci.ymlのtestの内容を変更することで対応した。

**Comment by a2308a2308** [comment]
```
Started with run options --seed 15807

ERROR ItemsControllerTest#test_should_create_item (1.37s)
Minitest::UnexpectedError:         NoMethodError: undefined method `question_items_url' for #<ItemsControllerTest:0x00007b6d497c7018>
            test/controllers/items_controller_test.rb:23:in `block (2 levels) in <class:ItemsControllerTest>'
            test/controllers/items_controller_test.rb:22:in `block in <class:ItemsControllerTest>'

ERROR ItemsControllerTest#test_should_get_index (1.38s)
Minitest::UnexpectedError:         NoMethodError: undefined method `question_items_url' for #<ItemsControllerTest:0x00007b6d498d0518>
            test/controllers/items_controller_test.rb:17:in `block in <class:ItemsControllerTest>'

ERROR ItemsControllerTest#test_should_not_create_item_with_invalid_data (1.39s)
Minitest::UnexpectedError:         NoMethodError: undefined method `question_items_url' for #<ItemsControllerTest:0x00007b6d496fc098>
            test/controllers/items_controller_test.rb:30:in `block (2 levels) in <class:ItemsControllerTest>'
```
とのエラー。

test/controllers/items_controller_test.rb のquestion_items_url　メソッドがないということ。
```{ruby}
  test 'should get index' do
    get question_items_url(@question)
    assert_response :success
  end

  test 'should create item' do
    assert_difference('Item.count', 1) do
      post question_items_url(@question), params: { item: { answer: 'New Answer', correct: false } }
    end
    assert_response :redirect
  end

  test 'should not create item with invalid data' do
    assert_no_difference('Item.count') do
      post question_items_url(@question), params: { item: { answer: '', correct: nil } }
    end
```

**Comment by a2308a2308** [comment]
- 不具合発生部分のテストは不要だったので削除いただき、解決した。
